### ISSUE TITLE
快速分享文件的服务 - Beam It

### ISSUE THREAD

**Issue by greatghoul** [greatghoul/profile#27]
荐哥今天要给朋友分享一个临时文件时，本来想用坚果云，但是想着分享后，还得确认对方有没有收到，然后再取消共享并且删除文件，感觉好麻烦，于是搜索了下有没有什么临时分享文件的服务，发现了 **Beamit** 这个神器。

<https://justbeamit.com/>

这是一个**阅后即焚**的文件分享服务，创建分享链接后 10 分钟或者有人下载了，就会自动删除文件。用来临时分享一些文件，再合适不过了。

![5cea14ed3ee9983520](https://user-images.githubusercontent.com/208966/58378285-315ce580-7fc4-11e9-9b7a-e4fa657ac33e.jpg)

虽然国内的访问速度不那么理想，但是好歹没有被墙。

**Comment by yitong-ovo** [comment]
很多时候我都用 https://send.firefox.com ... 还有第三方的 cli 客户端。

greatghoul <notifications@github.com> 于2019年5月26日周日 下午2:41写道：

**Comment by greatghoul** [comment]
我之前试过 send.firefox.com 不过手机上下载文件经常下载不下来， url 都是 blob 什么的。感觉还是有 bug.

除了这个外，我还有在用一个国内的服务，叫 http://tmp.link/ 感觉也还不错。
